# Application server ID
passwordless.corpId=1cfbf46170ca46ada90b2f18dab5f4e4
passwordless.serverId=1cfbf46170ca46ada90b2f18dab5f4e4


# Application server key (Only displayed once when changed)
passwordless.serverKey=e7e8dbb36b6b07d6


# URL to go to Simple UI screen (passwordless server - nginx)
passwordless.simpleAutopasswordUrl=http://192.168.0.243:8080


# Authentication server domain
passwordless.restCheckUrl=http://192.168.0.243:11040


# Push request server to connect to Websocket
passwordless.pushConnectorUrl=ws:192.168.0.243:15010


# Passwordless Recommended Specifications (ID/Password login prohibited when registering Passwordless) - 1: Applied, 0: Not Applied
passwordless.recommend=1
